# CAPÍTULO 2: PISO 26

- "...Gracias Marta. Me encuentro frente al edificio de la prestigiosa cadena multinacional ISR, que en estos momentos se haya en poder de un grupo terrorista, según fuentes del interior del propio edificio, de influencia británica. Desde ayer tarde la célula terrorista ha mantenido prisionero, se estima, a más de 1500 trabajadores de la cadena, entre reporteros, presentadores, equipo de limpieza, etc. Cuerpos especiales antiterroristas y de la policía trabajan codo con codo para intentar resolver la situación. Los intentos de negociaciones han sido en vano hasta ahora, pues los secuestradores se niegan a hablar. La tensión aumenta cada segundo, y creo que hablo en nombre de todos cuando deseo que esto termine de la mejor forma posible. Seguiremos informando. María Sanchez para el canal 5..."

Si cambiaba de canal, la misma historia. Juan acabó por rendirse ante la evidencia de que ninguna cadena se había mostrado indiferente ante la suculenta noticia sobre la toma del edificio. Se recostó en el cómodo sofá de cuero verde. A su lado, Alba, que no podía entender como su compañero estaba tan tranquilo.

- Tranquila. -Le había dicho, mordaz. -Estamos en la zona VIP.

Ciertamente era así, mientras el resto de trabajadores del edificio estaban retenidos en sus cubículos y oficinas desde hace casi un día -Ya iba siendo mediodía del día siguiente al secuestro-, Juan y Alba, gracias a la amistad del primero con el coronel, estaban “enchufados” en una de las oficinas de algún importante ejecutivo de la cadena. Dicho coronel estaba allí en la habitación, frente a ellos. Su nombre, Jack, para el único amigo que tenía en el edificio. En la puerta, a espaldas de los ya descritos, vigilaba incansable el soldado con el que el protagonista no había hecho buenas migas en un principio. Jhon, se les presentó, una vez el coronel le aseguró que no eran de los “malos”. Los dos jóvenes se miraban de vez en cuando -Juan desde el sillón, Jhon desde la puerta- y recordaban las largas conversaciones que habían establecido desde la noche anterior, en los momentos que el coronel se sentía generoso y dejaba al soldado descansar. 

- ¿Otra vez vagando en tus pensamientos? -Le dijo la chica, devolviéndole al presente. Ni siquiera había notado que Jack ya no estaba. Supuso, se habría ido a resolver algún asunto personalmente. Juan reintentó encontrar algo nuevo en la televisión, pero la noticia más importante vino del interior de esa misma habitación. La radio de Jhon, el soldado, comenzó a emitir interferencias, entre las cuales se podía distinguir la voz apresurada de alguien que estaba envuelto en disparos. 
- ¡Aquí equipo Alpha, nos están atacando!, repito, ¡Necesitamos ayuda, nos estan ataca...! -Jhon, el guardia, miró a su radio, alterado, alterado y confuso. Alba y Juan miraban fijamente desde el sillón. -¡Jhony, ¿estás bien?! ¡Dios mio, esto es una masacre! -Se oía a otro soldado, su voz se aproximaba al altavoz. -¡Ya lo han oido, el equipo Alpha necesita ayuda, en el piso 26!. -Se terminó la llamada. Las miradas de todos se centraron en la expresión de Jhon, tan dubitativa, tan impotente. En ese momento, Juan y el soldado parecieron recordar algo. -El coronel.- Dijeron al unísono, miraron al sillón rojo frente a ellos, estaba vacio. 

- Tengo que ir al piso 26 -Dijo el joven soldado, tratando de aparentar seriedad- Es mi obligación.
- Lo entiendo. -Respondió su amigo. -Iré contigo.
- ¡¿Qué dices?! ¡No puedo involucrar a civiles en esto!. -Ahora el que mostraba tranquilidad y seriedad, era Juan.
- Escucha, Jack, tu coronel es un buen amigo mío que ya me salvó la vida una vez, y quiero devolverle el favor. Es más... -Quiso enfatizar. -Tu, sin ir más lejos, eres una gran persona y tambien mi amigo. Y por ninguna circunstancia dejaré que vayas solo, tendrás que amarrarme, y eso llevaría tiempo, algo que no sobra ahora mismo.
- Jhon le miró a los ojos, dotados de una profunda convicción en lo que decía su boca. Solo esperó unos segundos con la atenta mirada de su amigo para responder.
- Está bien. Toma. -Le cedió una pistola. -No pienso dejarte indefenso.
- Ok. -Dijo Juan, suspirando, como preparándose. -¡Vamos!

Los dos amigos abrieron las puertas de par en par y empezaron a correr de cubículo en cubículo, entre un mar de trabajadores confusos y soldados nerviosos. No sabían que hacer ante la llamada de socorro que ellos también habían escuchado. Llegaron al largo y angosto pasillo que conducía al ascensor y esprintaron hacía él. El ascensor se abrió justo en ese instante, como si los estuviera esperando. Entraron rápidamente, y entre suspiros, Jhon apretó el botón número 26. Ninguno de los dos se esperaba la sorpresa. Alba, la chica de la que se habían olvidado para acudir a la llamada de socorro, entraba por la puerta con una rapidez y agilidad sorprendentes, a punto de cerrarse las puertas. Juan no podía creer lo que veía. 

- ¡¿Qué demonios haces?! -Exclamó Juan, con miedo de perderla allí a donde iban. No hubo respuesta por parte de ella, que estaba justo frente a la puerta. -¡¿Estás loca o qué?! -Fue inútil, Alba no respondía, estaba demasiado centrada en la puerta. Iban por el piso 24 cuando la chica se giró hacia Juan. -Lo siento- Le dijo. Esas palabras resonaron en la cabeza del joven, hasta instantes después, cuando las puertas se abrieron, y Alba comenzó a correr, decidida, entre un mar de balas que cruzaban de lado a lado la amplia habitación que les recibía. A cada uno de los lados, los dos grupos contendientes del tiroteo habían formado autenticas barricadas con mesas, sillas... y todo lo que encontraron. Juan pudo observar la horrible matanza que allí se estaba produciendo. La sangre encharcaba las paredes y el suelo, por donde corría entre los cadáveres mutilados. La horrible visión fue abrumadora para el joven, que comenzaba a ver borroso y a sentirse débil e impotente, a punto de desmayarse. Alba ya había desaparecido en alguna de las puertas del pasillo al fondo de la sala. 

Jhon, el soldado, que no se había dado cuenta del malestar de su amigo, intentaba distinguir a algún compañero del ejército entre las manos que disparaban sus armas por los huecos de las barricadas. Cuando se fijó en Juan, este estaba a punto de desmayarse, pero Jhon reaccionó a tiempo y le echó su brazo sobre el hombro. -Venga, aguanta. -Le dijo. -Que nos la jugamos. -Jhon lo llevó hasta la barricada de la derecha, deseando haber acertado y estar en el lugar correcto. El soldado se alegró al ver a sus camaradas allí -Todo lo que alguien podía alegrarse en una situación como esa-. Jhon soltó a su amigo en el suelo, apoyándolo contra la barricada y se incorporó para empezar a disparar junto con los demás soldados. En ese instante, Juan se desmayó. Ensordecido por el sonido de las balas, el joven perdió la conciencia  rodeado de un puñado de soldados que luchaban y morían por no se sabe que motivo.

